# official Python image
FROM python:3.9-slim

WORKDIR /app

# Copy all files from the code folder into the container
COPY code /app/code

# Run the Python script
CMD ["python", "/app/code/script.py"]
